//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3DoUong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBancaycanhEntities9 : DbContext
    {
        public QLBancaycanhEntities9()
            : base("name=QLBancaycanhEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHDN> CTHDNs { get; set; }
        public virtual DbSet<CTXuat> CTXuats { get; set; }
        public virtual DbSet<Giohang> Giohangs { get; set; }
        public virtual DbSet<HDNN> HDNNs { get; set; }
        public virtual DbSet<Hoadonxuat> Hoadonxuats { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<LoaiSP> LoaiSPs { get; set; }
        public virtual DbSet<Nhanvien> Nhanviens { get; set; }
        public virtual DbSet<Sanpham> Sanphams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tinchamsoccay> Tinchamsoccays { get; set; }
        public virtual DbSet<Usess> Usesses { get; set; }
    }
}
