//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3DoUong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTXuat
    {
        public int MaCTB { get; set; }
        public string MaHD { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual Hoadonxuat Hoadonxuat { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
