//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3DoUong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giohang
    {
        public int Magio { get; set; }
        public string Tensp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> Tong { get; set; }
        public Nullable<int> Masp { get; set; }
    }
}
