//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3DoUong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonxuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoadonxuat()
        {
            this.CTXuats = new HashSet<CTXuat>();
        }
    
        public string MaHD { get; set; }
        public string Hoten { get; set; }
        public string Diachi { get; set; }
        public Nullable<System.DateTime> NgaylapHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTXuat> CTXuats { get; set; }
    }
}
