//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3DoUong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public int MAKH { get; set; }
        public string TenKH { get; set; }
        public string SDTKH { get; set; }
        public string DiachiKH { get; set; }
        public string Email { get; set; }
    }
}
