//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3DoUong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhanvien()
        {
            this.HDNNs = new HashSet<HDNN>();
            this.Tinchamsoccays = new HashSet<Tinchamsoccay>();
        }
    
        public int MANV { get; set; }
        public string TenNV { get; set; }
        public string SDTNV { get; set; }
        public string DiachiKH { get; set; }
        public string Email { get; set; }
        public string AnhNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDNN> HDNNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tinchamsoccay> Tinchamsoccays { get; set; }
    }
}
