//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3DoUong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tinchamsoccay
    {
        public int Matin { get; set; }
        public string Tentin { get; set; }
        public string Anh { get; set; }
        public string Noidung { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
